public enum IMAGEPANEID // TypeDefIndex: 8489
{
	// Fields
	public int value__; // 0x0
	public const IMAGEPANEID img_title_start_off = 0;
	public const IMAGEPANEID img_title_start_on = 1;
	public const IMAGEPANEID img_title_conti_off = 2;
	public const IMAGEPANEID img_title_conti_on = 3;
	public const IMAGEPANEID img_title_conti_not = 4;
	public const IMAGEPANEID img_title_manual_off = 5;
	public const IMAGEPANEID img_title_manual_on = 6;
	public const IMAGEPANEID img_title_voice_off = 7;
	public const IMAGEPANEID img_title_voice_on = 8;
	public const IMAGEPANEID img_title_lang_off = 9;
	public const IMAGEPANEID img_title_lang_on = 10;
	public const IMAGEPANEID img_title_debug_off = 11;
	public const IMAGEPANEID img_title_debug_on = 12;
	public const IMAGEPANEID img_title_press_on = 13;
	public const IMAGEPANEID img_title_dlc_off = 14;
	public const IMAGEPANEID img_title_dlc_on = 15;
	public const IMAGEPANEID img_title_copyright = 16;
	public const IMAGEPANEID img_titlelogo_rf = 17;
	public const IMAGEPANEID img_titlelogo_rfSub = 18;
	public const IMAGEPANEID img_titlelogo_5 = 19;
	public const IMAGEPANEID img_titlelogo_5Bg = 20;
	public const IMAGEPANEID img_mainsenario_head = 21;
	public const IMAGEPANEID img_subsenario_head = 22;
	public const IMAGEPANEID img_lovesenario_head = 23;
	public const IMAGEPANEID img_hptext = 24;
	public const IMAGEPANEID img_rptext = 25;
	public const IMAGEPANEID img_northicon = 26;
	public const IMAGEPANEID img_next = 27;
	public const IMAGEPANEID img_wantedcomplete_big = 28;
	public const IMAGEPANEID img_wantedcomplete_small = 29;
	public const IMAGEPANEID img_calendar0 = 30;
	public const IMAGEPANEID img_calendar1 = 31;
	public const IMAGEPANEID img_calendar2 = 32;
	public const IMAGEPANEID img_calendar3 = 33;
	public const IMAGEPANEID img_calendar4 = 34;
	public const IMAGEPANEID img_calendar5 = 35;
	public const IMAGEPANEID img_hudordercompleted = 36;
	public const IMAGEPANEID img_hudorderfail = 37;
	public const IMAGEPANEID img_map_new = 38;
	public const IMAGEPANEID img_mini_tuto = 39;
	public const IMAGEPANEID img_mini_start = 40;
	public const IMAGEPANEID img_mini_finish = 41;
	public const IMAGEPANEID img_mini_perfect1 = 42;
	public const IMAGEPANEID img_mini_perfect2 = 43;
	public const IMAGEPANEID img_mini_perfect3 = 44;
	public const IMAGEPANEID img_mini_perfect4 = 45;
	public const IMAGEPANEID img_mini_success = 46;
	public const IMAGEPANEID img_mini_failed = 47;
	public const IMAGEPANEID img_mini_m = 48;
	public const IMAGEPANEID img_mini_win = 49;
	public const IMAGEPANEID img_mini_lose = 50;
	public const IMAGEPANEID img_mini_battle1 = 51;
	public const IMAGEPANEID img_mini_battle2 = 52;
	public const IMAGEPANEID img_mini_battle3 = 53;
	public const IMAGEPANEID img_symbol_new = 54;
	public const IMAGEPANEID Max = 55;
}

