[Serializable]
public enum NPCFindTargetDataID // TypeDefIndex: 7094
{
	// Fields
	public int value__; // 0x0
	public const NPCFindTargetDataID None = 0;
	public const NPCFindTargetDataID HateTarget = 1;
	public const NPCFindTargetDataID HateTarget_HP0 = 2;
	public const NPCFindTargetDataID Counterattack = 3;
	public const NPCFindTargetDataID SelfHPHigh0 = 4;
	public const NPCFindTargetDataID SelfHPUnder40 = 5;
	public const NPCFindTargetDataID SelfHPUnder50 = 6;
	public const NPCFindTargetDataID SelfHPUnder60 = 7;
	public const NPCFindTargetDataID SelfHPUnder70 = 8;
	public const NPCFindTargetDataID SelfHPUnder80 = 9;
	public const NPCFindTargetDataID PartyHPHigh0 = 10;
	public const NPCFindTargetDataID PartyHPUnder20 = 11;
	public const NPCFindTargetDataID PartyHPUnder30 = 12;
	public const NPCFindTargetDataID PartyHPUnder40 = 13;
	public const NPCFindTargetDataID PartyHPUnder50 = 14;
	public const NPCFindTargetDataID PartyPoisonHeal = 15;
	public const NPCFindTargetDataID PartySealHeal = 16;
	public const NPCFindTargetDataID PartyParalysisHeal = 17;
	public const NPCFindTargetDataID PartySleepHeal = 18;
	public const NPCFindTargetDataID PartyTrieHeal = 19;
	public const NPCFindTargetDataID PartySickHeal = 20;
	public const NPCFindTargetDataID Target_Change = 21;
	public const NPCFindTargetDataID Target_HPUnder30 = 22;
	public const NPCFindTargetDataID Target_act000 = 23;
	public const NPCFindTargetDataID Target_act000_HPUnder50 = 24;
	public const NPCFindTargetDataID Target_act005 = 25;
	public const NPCFindTargetDataID Target_act009_HPUnder50 = 26;
	public const NPCFindTargetDataID Target_act024 = 27;
	public const NPCFindTargetDataID Target_act024_HPUnder50 = 28;
	public const NPCFindTargetDataID Target_act025 = 29;
	public const NPCFindTargetDataID Target_act025_HPUnder50 = 30;
	public const NPCFindTargetDataID Target_act019_HPUnder50 = 31;
	public const NPCFindTargetDataID Target_act027 = 32;
	public const NPCFindTargetDataID Target_act028 = 33;
	public const NPCFindTargetDataID SelfLv30 = 34;
	public const NPCFindTargetDataID SelfLvUnder1000 = 35;
	public const NPCFindTargetDataID act000HPHigh0 = 36;
	public const NPCFindTargetDataID act000HPUnder40 = 37;
	public const NPCFindTargetDataID act000HPUnder50 = 38;
	public const NPCFindTargetDataID act001HPHigh0 = 39;
	public const NPCFindTargetDataID act001HPUnder50 = 40;
	public const NPCFindTargetDataID act002HPHigh0 = 41;
	public const NPCFindTargetDataID act002HPUnder40 = 42;
	public const NPCFindTargetDataID act008HPHigh0 = 43;
	public const NPCFindTargetDataID act008HPUnder40 = 44;
	public const NPCFindTargetDataID act020HPHigh0 = 45;
	public const NPCFindTargetDataID act020HPUnder50 = 46;
	public const NPCFindTargetDataID act024HPHigh0 = 47;
	public const NPCFindTargetDataID act024HPUnder40 = 48;
	public const NPCFindTargetDataID act000ParalysisHeal = 49;
	public const NPCFindTargetDataID act000PoisonHeal = 50;
	public const NPCFindTargetDataID act000SealHeal = 51;
	public const NPCFindTargetDataID act002ParalysisHeal = 52;
	public const NPCFindTargetDataID act002PoisonHeal = 53;
	public const NPCFindTargetDataID act002SealHeal = 54;
	public const NPCFindTargetDataID act008ParalysisHeal = 55;
	public const NPCFindTargetDataID act008PoisonHeal = 56;
	public const NPCFindTargetDataID act008SealHeal = 57;
	public const NPCFindTargetDataID act024ParalysisHeal = 58;
	public const NPCFindTargetDataID act024PoisonHeal = 59;
	public const NPCFindTargetDataID act024SealHeal = 60;
	public const NPCFindTargetDataID SelfParalysisHeal = 61;
	public const NPCFindTargetDataID SelfPoisonHeal = 62;
	public const NPCFindTargetDataID SelfSealHeal = 63;
	public const NPCFindTargetDataID EnemyLv100 = 64;
	public const NPCFindTargetDataID Max = 65;
}

