public abstract class SingletonMonoBehaviour<T> : MonoBehaviour // TypeDefIndex: 6865
{
	// Fields
	private static T _Instance; // 0x0

	// Properties
	public static T Instance { get; }

	// Methods

	// RVA: -1 Offset: -1
	public static T get_Instance() { }
	/* GenericInstMethod :
	|
	|-RVA: 0x2CAF590 Offset: 0x2CAF691 VA: 0x2CAF590
	|-SingletonMonoBehaviour<ActionSpeedManager>.get_Instance
	|-SingletonMonoBehaviour<ActorEquipManager>.get_Instance
	|-SingletonMonoBehaviour<ActorVoiceManager>.get_Instance
	|-SingletonMonoBehaviour<AdvBustupResManager>.get_Instance
	|-SingletonMonoBehaviour<AreaManager>.get_Instance
	|-SingletonMonoBehaviour<AvoidManager>.get_Instance
	|-SingletonMonoBehaviour<BaffamoDodgeManager>.get_Instance
	|-SingletonMonoBehaviour<BattleModeManager>.get_Instance
	|-SingletonMonoBehaviour<BeanSowingManager>.get_Instance
	|-SingletonMonoBehaviour<BehaviorTreeManager>.get_Instance
	|-SingletonMonoBehaviour<BitManager>.get_Instance
	|-SingletonMonoBehaviour<BulletManager>.get_Instance
	|-SingletonMonoBehaviour<CameraManager>.get_Instance
	|-SingletonMonoBehaviour<CharaEmotionManager>.get_Instance
	|-SingletonMonoBehaviour<CharaEscapeManager>.get_Instance
	|-SingletonMonoBehaviour<CharaFishingStateManager>.get_Instance
	|-SingletonMonoBehaviour<CharaLazyManager>.get_Instance
	|-SingletonMonoBehaviour<CharaPersonalMotionManager>.get_Instance
	|-SingletonMonoBehaviour<CharaSoulManager>.get_Instance
	|-SingletonMonoBehaviour<DamageTextManager>.get_Instance
	|-SingletonMonoBehaviour<DualSkillManager>.get_Instance
	|-SingletonMonoBehaviour<DualWorkMiniGame>.get_Instance
	|-SingletonMonoBehaviour<EffectManager>.get_Instance
	|-SingletonMonoBehaviour<EmotionManager>.get_Instance
	|-SingletonMonoBehaviour<EnvironmentSoundManager>.get_Instance
	|-SingletonMonoBehaviour<EscapeManager>.get_Instance
	|-SingletonMonoBehaviour<EventControllerBase>.get_Instance
	|-SingletonMonoBehaviour<EventTimelineManager>.get_Instance
	|-SingletonMonoBehaviour<FarmManager>.get_Instance
	|-SingletonMonoBehaviour<FarmChargeInteraction>.get_Instance
	|-SingletonMonoBehaviour<FarmSupportMonsterManager>.get_Instance
	|-SingletonMonoBehaviour<FestivalManager>.get_Instance
	|-SingletonMonoBehaviour<FieldItemSpawnDataManager>.get_Instance
	|-SingletonMonoBehaviour<FieldTreasureBoxManager>.get_Instance
	|-SingletonMonoBehaviour<IndoorShadowManager>.get_Instance
	|-SingletonMonoBehaviour<MaterialChangeTimeManager>.get_Instance
	|-SingletonMonoBehaviour<ObjectLoadManager>.get_Instance
	|-SingletonMonoBehaviour<VisibleChangeByFlagManager>.get_Instance
	|-SingletonMonoBehaviour<FishingManager>.get_Instance
	|-SingletonMonoBehaviour<FootStepsManager>.get_Instance
	|-SingletonMonoBehaviour<GameMain>.get_Instance
	|-SingletonMonoBehaviour<GimmickManager>.get_Instance
	|-SingletonMonoBehaviour<GluttonManager>.get_Instance
	|-SingletonMonoBehaviour<GrantAttributeManager>.get_Instance
	|-SingletonMonoBehaviour<GrapplingManager>.get_Instance
	|-SingletonMonoBehaviour<HUDDualWorkSelectInput>.get_Instance
	|-SingletonMonoBehaviour<HUDMapCalendarController>.get_Instance
	|-SingletonMonoBehaviour<HUDMinimapControl>.get_Instance
	|-SingletonMonoBehaviour<HandCuffsManager>.get_Instance
	|-SingletonMonoBehaviour<InputCursor>.get_Instance
	|-SingletonMonoBehaviour<InputLayerManager>.get_Instance
	|-SingletonMonoBehaviour<FurnitureManager>.get_Instance
	|-SingletonMonoBehaviour<ItemIconMng>.get_Instance
	|-SingletonMonoBehaviour<ItemStorageManager>.get_Instance
	|-SingletonMonoBehaviour<LoadingHintManager>.get_Instance
	|-SingletonMonoBehaviour<MagicManager>.get_Instance
	|-SingletonMonoBehaviour<MainScene>.get_Instance
	|-SingletonMonoBehaviour<MapIconMng>.get_Instance
	|-SingletonMonoBehaviour<MasterDataLoader>.get_Instance
	|-SingletonMonoBehaviour<MiningManager>.get_Instance
	|-SingletonMonoBehaviour<MobManager>.get_Instance
	|-SingletonMonoBehaviour<MobTravelerManager>.get_Instance
	|-SingletonMonoBehaviour<MonsterDoctor>.get_Instance
	|-SingletonMonoBehaviour<MonsterHutManager>.get_Instance
	|-SingletonMonoBehaviour<MonsterManager>.get_Instance
	|-SingletonMonoBehaviour<MonsterRideManager>.get_Instance
	|-SingletonMonoBehaviour<MoviePlayer>.get_Instance
	|-SingletonMonoBehaviour<NpcDataManager>.get_Instance
	|-SingletonMonoBehaviour<NpcLifecycleController>.get_Instance
	|-SingletonMonoBehaviour<NpcPatrolPointManager>.get_Instance
	|-SingletonMonoBehaviour<OnGroundItemManager>.get_Instance
	|-SingletonMonoBehaviour<OrderManager>.get_Instance
	|-SingletonMonoBehaviour<PartnerManager>.get_Instance
	|-SingletonMonoBehaviour<PauseManager>.get_Instance
	|-SingletonMonoBehaviour<PetManager>.get_Instance
	|-SingletonMonoBehaviour<PlayerInteractionCollider>.get_Instance
	|-SingletonMonoBehaviour<PlayerTrackingCamera>.get_Instance
	|-SingletonMonoBehaviour<PreloadMasterDataLoader>.get_Instance
	|-SingletonMonoBehaviour<RF5MoviePlayer>.get_Instance
	|-SingletonMonoBehaviour<ShippingManager>.get_Instance
	|-SingletonMonoBehaviour<SubtitleManager>.get_Instance
	|-SingletonMonoBehaviour<RestraintManager>.get_Instance
	|-SingletonMonoBehaviour<ScreenFadeManager>.get_Instance
	|-SingletonMonoBehaviour<SeasonManager>.get_Instance
	|-SingletonMonoBehaviour<SeedSupportManager>.get_Instance
	|-SingletonMonoBehaviour<SkillManager>.get_Instance
	|-SingletonMonoBehaviour<SkyStudioTimeManager>.get_Instance
	|-SingletonMonoBehaviour<SlowStateManager>.get_Instance
	|-SingletonMonoBehaviour<SnowmanManager>.get_Instance
	|-SingletonMonoBehaviour<SoundManager>.get_Instance
	|-SingletonMonoBehaviour<SpringGeneralManager>.get_Instance
	|-SingletonMonoBehaviour<StateMachineWorkerManager>.get_Instance
	|-SingletonMonoBehaviour<SuperArmorManager>.get_Instance
	|-SingletonMonoBehaviour<SymbolObjectManager>.get_Instance
	|-SingletonMonoBehaviour<object>.get_Instance
	|-SingletonMonoBehaviour<TeleportAreaManager>.get_Instance
	|-SingletonMonoBehaviour<ThrottleManager>.get_Instance
	|-SingletonMonoBehaviour<TimeManager>.get_Instance
	|-SingletonMonoBehaviour<TimeScaleManager>.get_Instance
	|-SingletonMonoBehaviour<TitleMenu>.get_Instance
	|-SingletonMonoBehaviour<TutorialManager>.get_Instance
	|-SingletonMonoBehaviour<UIItemAutoPick>.get_Instance
	|-SingletonMonoBehaviour<UIItemSlotsManager>.get_Instance
	|-SingletonMonoBehaviour<UILight>.get_Instance
	|-SingletonMonoBehaviour<UIMainController>.get_Instance
	|-SingletonMonoBehaviour<UIMainManager>.get_Instance
	|-SingletonMonoBehaviour<YawnManager>.get_Instance
	*/

	// RVA: -1 Offset: -1 Slot: 4
	protected virtual void Awake() { }
	/* GenericInstMethod :
	|
	|-RVA: 0x2CAF7D0 Offset: 0x2CAF8D1 VA: 0x2CAF7D0
	|-SingletonMonoBehaviour<ActionSpeedManager>.Awake
	|-SingletonMonoBehaviour<ActorEquipManager>.Awake
	|-SingletonMonoBehaviour<ActorVoiceManager>.Awake
	|-SingletonMonoBehaviour<AdvBustupResManager>.Awake
	|-SingletonMonoBehaviour<AreaManager>.Awake
	|-SingletonMonoBehaviour<AvoidManager>.Awake
	|-SingletonMonoBehaviour<BattleModeManager>.Awake
	|-SingletonMonoBehaviour<BehaviorTreeManager>.Awake
	|-SingletonMonoBehaviour<BitManager>.Awake
	|-SingletonMonoBehaviour<BulletManager>.Awake
	|-SingletonMonoBehaviour<CameraManager>.Awake
	|-SingletonMonoBehaviour<CharaEmotionManager>.Awake
	|-SingletonMonoBehaviour<CharaEscapeManager>.Awake
	|-SingletonMonoBehaviour<CharaFishingStateManager>.Awake
	|-SingletonMonoBehaviour<CharaLazyManager>.Awake
	|-SingletonMonoBehaviour<CharaPersonalMotionManager>.Awake
	|-SingletonMonoBehaviour<CharaSoulManager>.Awake
	|-SingletonMonoBehaviour<CharacterNearCulling_Camera>.Awake
	|-SingletonMonoBehaviour<DamageTextManager>.Awake
	|-SingletonMonoBehaviour<DualSkillManager>.Awake
	|-SingletonMonoBehaviour<DualWorkMiniGame>.Awake
	|-SingletonMonoBehaviour<EffectManager>.Awake
	|-SingletonMonoBehaviour<EmotionManager>.Awake
	|-SingletonMonoBehaviour<EnvironmentSoundManager>.Awake
	|-SingletonMonoBehaviour<EscapeManager>.Awake
	|-SingletonMonoBehaviour<EventControllerBase>.Awake
	|-SingletonMonoBehaviour<EventTimelineManager>.Awake
	|-SingletonMonoBehaviour<FarmManager>.Awake
	|-SingletonMonoBehaviour<FarmChargeInteraction>.Awake
	|-SingletonMonoBehaviour<FarmSupportMonsterManager>.Awake
	|-SingletonMonoBehaviour<IndoorShadowManager>.Awake
	|-SingletonMonoBehaviour<MaterialChangeTimeManager>.Awake
	|-SingletonMonoBehaviour<ObjectLoadManager>.Awake
	|-SingletonMonoBehaviour<VisibleChangeByFlagManager>.Awake
	|-SingletonMonoBehaviour<FishingManager>.Awake
	|-SingletonMonoBehaviour<FootStepsManager>.Awake
	|-SingletonMonoBehaviour<GimmickManager>.Awake
	|-SingletonMonoBehaviour<GrantAttributeManager>.Awake
	|-SingletonMonoBehaviour<GrapplingManager>.Awake
	|-SingletonMonoBehaviour<HUDDualWorkSelectInput>.Awake
	|-SingletonMonoBehaviour<HUDMapCalendarController>.Awake
	|-SingletonMonoBehaviour<HUDMinimapControl>.Awake
	|-SingletonMonoBehaviour<HandCuffsManager>.Awake
	|-SingletonMonoBehaviour<InputCursor>.Awake
	|-SingletonMonoBehaviour<InputLayerManager>.Awake
	|-SingletonMonoBehaviour<FurnitureManager>.Awake
	|-SingletonMonoBehaviour<ItemIconMng>.Awake
	|-SingletonMonoBehaviour<LoadingHintManager>.Awake
	|-SingletonMonoBehaviour<MagicManager>.Awake
	|-SingletonMonoBehaviour<MapIconMng>.Awake
	|-SingletonMonoBehaviour<MasterDataLoader>.Awake
	|-SingletonMonoBehaviour<MiningManager>.Awake
	|-SingletonMonoBehaviour<MobManager>.Awake
	|-SingletonMonoBehaviour<MobTravelerManager>.Awake
	|-SingletonMonoBehaviour<MonsterDoctor>.Awake
	|-SingletonMonoBehaviour<MonsterHutManager>.Awake
	|-SingletonMonoBehaviour<MonsterManager>.Awake
	|-SingletonMonoBehaviour<MonsterRideManager>.Awake
	|-SingletonMonoBehaviour<MoviePlayer>.Awake
	|-SingletonMonoBehaviour<NpcDataManager>.Awake
	|-SingletonMonoBehaviour<OnGroundItemManager>.Awake
	|-SingletonMonoBehaviour<OrderManager>.Awake
	|-SingletonMonoBehaviour<PartnerManager>.Awake
	|-SingletonMonoBehaviour<PauseManager>.Awake
	|-SingletonMonoBehaviour<PlayerInteractionCollider>.Awake
	|-SingletonMonoBehaviour<PlayerLockonCamera>.Awake
	|-SingletonMonoBehaviour<PreloadMasterDataLoader>.Awake
	|-SingletonMonoBehaviour<RF5MoviePlayer>.Awake
	|-SingletonMonoBehaviour<ShippingManager>.Awake
	|-SingletonMonoBehaviour<SubtitleManager>.Awake
	|-SingletonMonoBehaviour<RestraintManager>.Awake
	|-SingletonMonoBehaviour<SceneAsyncLoadController>.Awake
	|-SingletonMonoBehaviour<ScreenFadeManager>.Awake
	|-SingletonMonoBehaviour<SeasonManager>.Awake
	|-SingletonMonoBehaviour<SeedSupportManager>.Awake
	|-SingletonMonoBehaviour<SkillManager>.Awake
	|-SingletonMonoBehaviour<SkyStudioTimeManager>.Awake
	|-SingletonMonoBehaviour<SlowStateManager>.Awake
	|-SingletonMonoBehaviour<SoundManager>.Awake
	|-SingletonMonoBehaviour<SpringGeneralManager>.Awake
	|-SingletonMonoBehaviour<SpriteAssetLoader>.Awake
	|-SingletonMonoBehaviour<StateMachineWorkerManager>.Awake
	|-SingletonMonoBehaviour<SuperArmorManager>.Awake
	|-SingletonMonoBehaviour<SymbolObjectManager>.Awake
	|-SingletonMonoBehaviour<object>.Awake
	|-SingletonMonoBehaviour<TeleportAreaManager>.Awake
	|-SingletonMonoBehaviour<ThrottleManager>.Awake
	|-SingletonMonoBehaviour<TimeManager>.Awake
	|-SingletonMonoBehaviour<TimeScaleManager>.Awake
	|-SingletonMonoBehaviour<TitleMenu>.Awake
	|-SingletonMonoBehaviour<TutorialManager>.Awake
	|-SingletonMonoBehaviour<UIItemAutoPick>.Awake
	|-SingletonMonoBehaviour<UIItemSlotsManager>.Awake
	|-SingletonMonoBehaviour<UILight>.Awake
	|-SingletonMonoBehaviour<UIMainController>.Awake
	|-SingletonMonoBehaviour<UIMainManager>.Awake
	|-SingletonMonoBehaviour<YawnManager>.Awake
	*/

	// RVA: -1 Offset: -1
	protected bool CheckInstance() { }
	/* GenericInstMethod :
	|
	|-RVA: 0x2CAF800 Offset: 0x2CAF901 VA: 0x2CAF800
	|-SingletonMonoBehaviour<FieldItemSpawnDataManager>.CheckInstance
	|-SingletonMonoBehaviour<FieldTreasureBoxManager>.CheckInstance
	|-SingletonMonoBehaviour<SkyStudioTimeManager>.CheckInstance
	|-SingletonMonoBehaviour<object>.CheckInstance
	*/

	// RVA: -1 Offset: -1
	protected void .ctor() { }
	/* GenericInstMethod :
	|
	|-RVA: 0x2CAF9D0 Offset: 0x2CAFAD1 VA: 0x2CAF9D0
	|-SingletonMonoBehaviour<ActionSpeedManager>..ctor
	|-SingletonMonoBehaviour<ActorEquipManager>..ctor
	|-SingletonMonoBehaviour<ActorVoiceManager>..ctor
	|-SingletonMonoBehaviour<AdvBustupResManager>..ctor
	|-SingletonMonoBehaviour<AreaManager>..ctor
	|-SingletonMonoBehaviour<AvoidManager>..ctor
	|-SingletonMonoBehaviour<BaffamoDodgeManager>..ctor
	|-SingletonMonoBehaviour<BattleModeManager>..ctor
	|-SingletonMonoBehaviour<BeanSowingManager>..ctor
	|-SingletonMonoBehaviour<BehaviorTreeManager>..ctor
	|-SingletonMonoBehaviour<BitManager>..ctor
	|-SingletonMonoBehaviour<BulletManager>..ctor
	|-SingletonMonoBehaviour<CameraManager>..ctor
	|-SingletonMonoBehaviour<CharaEmotionManager>..ctor
	|-SingletonMonoBehaviour<CharaEscapeManager>..ctor
	|-SingletonMonoBehaviour<CharaFishingStateManager>..ctor
	|-SingletonMonoBehaviour<CharaLazyManager>..ctor
	|-SingletonMonoBehaviour<CharaPersonalMotionManager>..ctor
	|-SingletonMonoBehaviour<CharaSoulManager>..ctor
	|-SingletonMonoBehaviour<CharacterNearCulling_Camera>..ctor
	|-SingletonMonoBehaviour<DamageTextManager>..ctor
	|-SingletonMonoBehaviour<DualSkillManager>..ctor
	|-SingletonMonoBehaviour<DualWorkMiniGame>..ctor
	|-SingletonMonoBehaviour<EffectManager>..ctor
	|-SingletonMonoBehaviour<EmotionManager>..ctor
	|-SingletonMonoBehaviour<EnvironmentSoundManager>..ctor
	|-SingletonMonoBehaviour<EscapeManager>..ctor
	|-SingletonMonoBehaviour<EventControllerBase>..ctor
	|-SingletonMonoBehaviour<EventTimelineManager>..ctor
	|-SingletonMonoBehaviour<FarmManager>..ctor
	|-SingletonMonoBehaviour<FarmChargeInteraction>..ctor
	|-SingletonMonoBehaviour<FarmSupportMonsterManager>..ctor
	|-SingletonMonoBehaviour<FestivalManager>..ctor
	|-SingletonMonoBehaviour<FieldItemSpawnDataManager>..ctor
	|-SingletonMonoBehaviour<FieldTreasureBoxManager>..ctor
	|-SingletonMonoBehaviour<IndoorShadowManager>..ctor
	|-SingletonMonoBehaviour<MaterialChangeTimeManager>..ctor
	|-SingletonMonoBehaviour<ObjectLoadManager>..ctor
	|-SingletonMonoBehaviour<VisibleChangeByFlagManager>..ctor
	|-SingletonMonoBehaviour<FishingManager>..ctor
	|-SingletonMonoBehaviour<FocusObjectInteractionAccesser>..ctor
	|-SingletonMonoBehaviour<FootStepsManager>..ctor
	|-SingletonMonoBehaviour<GameMain>..ctor
	|-SingletonMonoBehaviour<GimmickManager>..ctor
	|-SingletonMonoBehaviour<GluttonManager>..ctor
	|-SingletonMonoBehaviour<GrantAttributeManager>..ctor
	|-SingletonMonoBehaviour<GrapplingManager>..ctor
	|-SingletonMonoBehaviour<HUDDualWorkSelectInput>..ctor
	|-SingletonMonoBehaviour<HUDMapCalendarController>..ctor
	|-SingletonMonoBehaviour<HUDMinimapControl>..ctor
	|-SingletonMonoBehaviour<HandCuffsManager>..ctor
	|-SingletonMonoBehaviour<InputCursor>..ctor
	|-SingletonMonoBehaviour<InputLayerManager>..ctor
	|-SingletonMonoBehaviour<FurnitureManager>..ctor
	|-SingletonMonoBehaviour<ItemIconMng>..ctor
	|-SingletonMonoBehaviour<ItemStorageManager>..ctor
	|-SingletonMonoBehaviour<LoadingHintManager>..ctor
	|-SingletonMonoBehaviour<MagicManager>..ctor
	|-SingletonMonoBehaviour<MainScene>..ctor
	|-SingletonMonoBehaviour<MapIconMng>..ctor
	|-SingletonMonoBehaviour<MiningManager>..ctor
	|-SingletonMonoBehaviour<MobManager>..ctor
	|-SingletonMonoBehaviour<MobTravelerManager>..ctor
	|-SingletonMonoBehaviour<MonsterDoctor>..ctor
	|-SingletonMonoBehaviour<MonsterHutManager>..ctor
	|-SingletonMonoBehaviour<MonsterManager>..ctor
	|-SingletonMonoBehaviour<MonsterRideManager>..ctor
	|-SingletonMonoBehaviour<MoviePlayer>..ctor
	|-SingletonMonoBehaviour<NpcDataManager>..ctor
	|-SingletonMonoBehaviour<NpcLifecycleController>..ctor
	|-SingletonMonoBehaviour<NpcPatrolPointManager>..ctor
	|-SingletonMonoBehaviour<OnGroundItemManager>..ctor
	|-SingletonMonoBehaviour<OrderManager>..ctor
	|-SingletonMonoBehaviour<PartnerManager>..ctor
	|-SingletonMonoBehaviour<PauseManager>..ctor
	|-SingletonMonoBehaviour<PetManager>..ctor
	|-SingletonMonoBehaviour<PlayerFarmingCamera>..ctor
	|-SingletonMonoBehaviour<PlayerInteractionCollider>..ctor
	|-SingletonMonoBehaviour<PlayerLockonCamera>..ctor
	|-SingletonMonoBehaviour<PlayerTrackingCamera>..ctor
	|-SingletonMonoBehaviour<RF5MoviePlayer>..ctor
	|-SingletonMonoBehaviour<ShippingManager>..ctor
	|-SingletonMonoBehaviour<SubtitleManager>..ctor
	|-SingletonMonoBehaviour<RestraintManager>..ctor
	|-SingletonMonoBehaviour<SceneAsyncLoadController>..ctor
	|-SingletonMonoBehaviour<ScreenFadeManager>..ctor
	|-SingletonMonoBehaviour<SeasonManager>..ctor
	|-SingletonMonoBehaviour<SeedSupportManager>..ctor
	|-SingletonMonoBehaviour<SkillManager>..ctor
	|-SingletonMonoBehaviour<SkyStudioTimeManager>..ctor
	|-SingletonMonoBehaviour<SlowStateManager>..ctor
	|-SingletonMonoBehaviour<SnowmanManager>..ctor
	|-SingletonMonoBehaviour<SoundManager>..ctor
	|-SingletonMonoBehaviour<SpringGeneralManager>..ctor
	|-SingletonMonoBehaviour<SpriteAssetLoader>..ctor
	|-SingletonMonoBehaviour<StateMachineWorkerManager>..ctor
	|-SingletonMonoBehaviour<SuperArmorManager>..ctor
	|-SingletonMonoBehaviour<SymbolObjectManager>..ctor
	|-SingletonMonoBehaviour<object>..ctor
	|-SingletonMonoBehaviour<TeleportAreaManager>..ctor
	|-SingletonMonoBehaviour<ThrottleManager>..ctor
	|-SingletonMonoBehaviour<TimeManager>..ctor
	|-SingletonMonoBehaviour<TimeScaleManager>..ctor
	|-SingletonMonoBehaviour<TitleMenu>..ctor
	|-SingletonMonoBehaviour<TutorialManager>..ctor
	|-SingletonMonoBehaviour<UIItemAutoPick>..ctor
	|-SingletonMonoBehaviour<UIItemSlotsManager>..ctor
	|-SingletonMonoBehaviour<UILight>..ctor
	|-SingletonMonoBehaviour<UIMainController>..ctor
	|-SingletonMonoBehaviour<UIMainManager>..ctor
	|-SingletonMonoBehaviour<YawnManager>..ctor
	*/
}

