public enum Sprites // TypeDefIndex: 10242
{
	// Fields
	public int value__; // 0x0
	public const Sprites NONE = 0;
	public const Sprites ICON_FACEICONSPRITEATLAS = 19740;
	public const Sprites ICON_ICONSPRITEATLAS_BUILDERITEMICON = 19741;
	public const Sprites ICON_ICONSPRITEATLAS_FURNITUREITEMICON = 19742;
	public const Sprites ICON_ICONSPRITEATLAS_NPCCHILDICON = 19743;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS000 = 19744;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS001 = 19745;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS002 = 19746;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS003 = 19747;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS004 = 19748;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS005 = 19749;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS006 = 19750;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS007 = 19751;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS008 = 19752;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS009 = 19753;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS010 = 19754;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS011 = 19755;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS012 = 19756;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS013 = 19757;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS014 = 19758;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS015 = 19759;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS016 = 19760;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS017 = 19761;
	public const Sprites ICON_ITEMICONSSPRITEATLAS_ITEMICONSPRITEATLAS018 = 19762;
	public const Sprites ICON_MONSTERFACEICONSPRITEATLAS = 19763;
	public const Sprites ICON_STAMPICONSPRITEATLAS = 19764;
	public const Sprites ICON_WANTEDMONSTERSPRITEATLAS = 19765;
	public const Sprites MOVIEPREVIEWIMAGE_MOVIESPRITEATLAS = 19766;
}

