public enum BUSTUPID // TypeDefIndex: 10686
{
	// Fields
	public int value__; // 0x0
	public const BUSTUPID Ares = 0;
	public const BUSTUPID Alice = 1;
	public const BUSTUPID Priscilla = 2;
	public const BUSTUPID Lucy = 3;
	public const BUSTUPID Scarlett = 4;
	public const BUSTUPID Fuqua = 5;
	public const BUSTUPID Beatrice = 6;
	public const BUSTUPID Ludmila = 7;
	public const BUSTUPID Martin = 8;
	public const BUSTUPID Cecile = 9;
	public const BUSTUPID Murakumo = 10;
	public const BUSTUPID Lyka = 11;
	public const BUSTUPID Reinhard = 12;
	public const BUSTUPID Lucas = 13;
	public const BUSTUPID Elsje = 14;
	public const BUSTUPID Palmo = 15;
	public const BUSTUPID Heinz = 16;
	public const BUSTUPID Randolph = 17;
	public const BUSTUPID Yuki = 18;
	public const BUSTUPID Simone = 19;
	public const BUSTUPID Misasagi = 20;
	public const BUSTUPID Terry = 21;
	public const BUSTUPID Rivia = 22;
	public const BUSTUPID Riviachiron = 23;
	public const BUSTUPID Laedia = 24;
	public const BUSTUPID Laevadia = 25;
	public const BUSTUPID Doug = 26;
	public const BUSTUPID Julien = 27;
	public const BUSTUPID Hina = 28;
	public const BUSTUPID Baby = 29;
	public const BUSTUPID ChildBoy = 30;
	public const BUSTUPID ChildGirl = 31;
	public const BUSTUPID Dag = 32;
	public const BUSTUPID Marguerite = 33;
	public const BUSTUPID Oswald = 34;
	public const BUSTUPID Gandage = 35;
	public const BUSTUPID Max = 36;
	public const BUSTUPID FirstBaby = 37;
	public const BUSTUPID BoyBaby = 38;
	public const BUSTUPID GirlBaby = 39;
	public const BUSTUPID BustupDebugMax = 40;
	public const BUSTUPID BustupSet2 = 36;
	public const BUSTUPID Ares2 = 36;
	public const BUSTUPID Alice2 = 37;
	public const BUSTUPID Priscilla2 = 38;
	public const BUSTUPID Fuqua2 = 39;
	public const BUSTUPID Ludmila2 = 40;
	public const BUSTUPID Lyka2 = 41;
	public const BUSTUPID Lucas2 = 42;
	public const BUSTUPID Martin2 = 43;
	public const BUSTUPID Rivia2 = 44;
	public const BUSTUPID BustupSet3 = 45;
	public const BUSTUPID Fuqua3 = 45;
	public const BUSTUPID BustupDataMax = 46;
	public const BUSTUPID ChildBoyMouth01 = 46;
	public const BUSTUPID ChildBoyMouth02 = 47;
	public const BUSTUPID ChildBoyMouth03 = 48;
	public const BUSTUPID ChildGirlMouth01 = 49;
	public const BUSTUPID ChildGirlMouth02 = 50;
	public const BUSTUPID ChildGirlMouth03 = 51;
	public const BUSTUPID MaxMouthVar = 52;
}

